export const education = {
  mainlyFormation: {
    institute: 'Universidade Estadual da Paraíba',
    instituteLogo: 'assets/img/education/uepb.png',
    course: 'Computer science',
    courseTotalHours: 3570,
    startedAt: '10/02/2015',
    endedAt: '20/12/2022',
    pathCourse: 'https://departamentos.uepb.edu.br/comp-ccea/grade-curricular',
  },
  secondaryFormation: [
    {
      courseName: 'Curso Web Moderno Completo com JavaScript.',
      totalHours: 97.5,
      coveredTopics: [
        'Javascript',
        'Node',
        'Express',
        'HTML',
        'CSS',
        'Webpack',
        'JQuery',
        'Bootstrap',
        'React',
        'Vue',
        'Angular',
        'MySQL',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/web1.png',
      courseUrl: 'https://www.udemy.com/course/curso-web',
    },
    {
      courseName: 'Curso de VueJS - O guia completo.',
      totalHours: 43,
      coveredTopics: ['Javascript', 'VueJS', 'Vuex', 'HTML', 'CSS'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/vue.png',
      courseUrl: 'https://www.udemy.com/course/vue-js-completo',
    },
    {
      courseName: 'Curso de React + Redux: Fundamentos.',
      totalHours: 54,
      coveredTopics: [
        'Javascript',
        'React',
        'Redux',
        'Hooks',
        'MongoDB',
        'HTML',
        'CSS',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/react-redux.png',
      courseUrl: 'https://www.udemy.com/course/react-redux-pt',
    },
    {
      courseName: 'JavaScript Funcional e Reativo.',
      totalHours: 17,
      coveredTopics: ['Javascript', 'Programação funcional', 'RXJS'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/js.png',
      courseUrl: 'https://www.udemy.com/course/javascript-funcional',
    },
    {
      courseName: 'Certificação AWS Desenvolvedor - Associate.',
      totalHours: 23.5,
      coveredTopics: [
        'ECS',
        'DynamoDB',
        'Lambda',
        'S3',
        'Cloudfront',
        'Elastic cache',
        'API Gateway',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/aws.png',
      courseUrl: 'https://www.udemy.com/course/aws-developer/',
    },
    {
      courseName: 'Testes unitários em JAVA: Domine JUnit, Mockito e TDD.',
      totalHours: 8,
      coveredTopics: ['Java', 'JUnit', 'Mockito', 'TDD'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/junit.png',
      courseUrl: 'https://www.udemy.com/course/testes-unitarios-em-java/',
    },
    {
      courseName:
        'Spring Boot + React JS: Desenvolva Aplicações Web Completas.',
      totalHours: 22.5,
      coveredTopics: [
        'Java',
        'Spring',
        'Hibernate',
        'JPA',
        'JUnit',
        'React',
        'HTML',
        'CSS',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/spring.png',
      courseUrl:
        'https://www.udemy.com/course/desenvolva-aplicacoes-completas-com-spring-boot-e-react-js',
    },
    {
      courseName: 'Git e Github Essencial para o Desenvolvedor.',
      totalHours: 12,
      coveredTopics: ['Git', 'Github'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/git.png',
      courseUrl: 'https://www.udemy.com/course/curso-de-git-e-github-essencial',
    },
    {
      courseName: 'Figma Design de interfaces do zero ao profissional.',
      totalHours: 14.5,
      coveredTopics: ['Figma', 'UI/UX'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/figma.png',
      courseUrl: 'https://www.udemy.com/course/figma-design-interfaces',
    },
    {
      courseName: 'Linux TOTAL: dos primeiros passos aos comandos avançados.',
      totalHours: 10.5,
      coveredTopics: ['Linux', 'Ubuntu', 'Fedora', 'Gnome'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/linux.png',
      courseUrl:
        'https://www.udemy.com/course/linux-total-dos-primeiros-passos-aos-comandos-avancados',
    },
    {
      courseName: 'Java completo: Do Zero ao Profissional.',
      totalHours: 77,
      coveredTopics: [
        'Java',
        'OO',
        'MySQL',
        'MongoDB',
        'Spring Boot',
        'JavaFX',
        'JDBC',
        'JPA',
        'Hibernate',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/java.png',
      courseUrl:
        'https://www.udemy.com/course/fundamentos-de-programacao-com-java',
    },
    {
      courseName: 'React Native: Desenvolva APPs Nativas para Android e iOS',
      totalHours: 45,
      coveredTopics: ['JavaScript', 'React Native', 'Expo'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/mobile.png',
      courseUrl: 'https://www.udemy.com/course/curso-react-native',
    },
    {
      courseName: 'Curso de React.Js e Next.Js',
      totalHours: 93,
      coveredTopics: [
        'ReactJS',
        'NextJS',
        'Styled-Components',
        'Jest',
        'HTML',
        'CSS',
        'TypeScript',
        'JavaScript',
      ],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/web2.png',
      courseUrl:
        'https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/',
    },
    {
      courseName: 'Fundamentos de Ethical Hacking',
      totalHours: 25,
      coveredTopics: ['Hacking', 'Pentest', 'Linux', 'Netcat', 'Metasploit'],
      plataform: 'Udemy',
      courseImage: 'assets/img/education/hacking.png',
      courseUrl: 'https://www.udemy.com/course/fundamentos-de-ethical-hacking/',
    },
  ],
};
